"""Keep the Play report template identical to the existing offline UI."""
import argparse,json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
expected='// Generated by sync-template.py. Edit assets/tuning.html, then regenerate.\nexport const TEMPLATE = '+json.dumps((root/'assets/tuning.html').read_text(),ensure_ascii=True)+';\n'
expected+='export const LEGACY_TEMPLATE = '+json.dumps((root/'assets/review.html').read_text(),ensure_ascii=True)+';\n'
target=Path(__file__).with_name('generatedtemplate.ts')
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
if args.check:
 if not target.exists() or target.read_text()!=expected:raise SystemExit('Report template drift. Run plays/sync-template.py.')
 print('Report template matches assets/tuning.html.')
else:target.write_text(expected)
